# Generated by Django 4.1.4 on 2022-12-11 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Database_credentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_type', models.CharField(blank=True, max_length=100, null=True)),
                ('host', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('database', models.CharField(blank=True, max_length=100, null=True)),
                ('mongourl', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
