# Generated by Django 4.1.4 on 2022-12-11 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_database_credentials_auth_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database_credentials',
            name='auth_user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
