# Generated by Django 4.1.4 on 2022-12-14 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_delete_basic_auth'),
    ]

    operations = [
        migrations.AddField(
            model_name='database_credentials',
            name='port',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
