# Generated by Django 4.1.4 on 2022-12-10 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='database_name',
            name='table',
        ),
        migrations.AddField(
            model_name='database_name',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='generate.table_name'),
        ),
    ]
