# Generated by Django 4.1.4 on 2022-12-11 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate', '0006_alter_temp_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='temp',
            name='freq_delete_query',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='temp',
            name='freq_insert_query',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='temp',
            name='freq_select_query',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='temp',
            name='freq_tables',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='temp',
            name='freq_update_query',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='temp',
            name='max_time',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='temp',
            name='mean_time',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='temp',
            name='min_time',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
