# Generated by Django 4.1.4 on 2022-12-11 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate', '0003_remove_database_name_table_database_name_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
