# Generated by Django 4.1.4 on 2022-12-13 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generate', '0011_results_db_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Database_Name',
        ),
        migrations.DeleteModel(
            name='Table_Name',
        ),
    ]
