# Generated by Django 4.1.4 on 2022-12-14 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_basic_auth'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Basic_auth',
        ),
    ]
